var panaPtzCommands = [
    {commandResponse : 'axf', commandName : 'Focus Position' },
    {commandResponse : 'axz', commandName : 'Zoom Position' },
    {commandResponse : 'CGI_TIME:', commandName : 'CGI send interval' },
    {commandResponse : 'd1', commandName : 'Auto focus On/Off' },
    {commandResponse : 'd2', commandName : '' },
    {commandResponse : 'd3', commandName : 'Auto Iris On/Off' },
    {commandResponse : 'd4', commandName : '' },
    {commandResponse : 'd6', commandName : 'Option SW' },
    {commandResponse : 'iNS', commandName : 'Installation position' },
    {commandResponse : 'lC1', commandName : 'Movement range limit On/Off up' },
    {commandResponse : 'lC2', commandName : 'Movement range limit On/Off down' },
    {commandResponse : 'lC3', commandName : 'Movement range limit On/Off left' },
    {commandResponse : 'lC4', commandName : 'Movement range limit On/Off right' },
    {commandResponse : 'OAW:', commandName : 'AWB (AWC) Mode' },
    {commandResponse : 'OBI:', commandName : 'B gain' },
    {commandResponse : 'OBP:', commandName : 'B pedestal' },
    {commandResponse : 'OBR:', commandName : 'Color bar/Camera' },
    {commandResponse : 'ODT:', commandName : 'Detail' },
    {commandResponse : 'OER:', commandName : 'Error Notice' },
    {commandResponse : 'OGU:', commandName : 'Gain' },
    {commandResponse : 'OID:', commandName : 'Model number' },
    {commandResponse : 'ORI:', commandName : 'R gain' },
    {commandResponse : 'ORP:', commandName : 'R pedestal' },
    {commandResponse : 'OSA:30:', commandName : 'Master Detail' },
    {commandResponse : 'OSA:87:', commandName : 'Format' },
    {commandResponse : 'OSD:4F:', commandName : 'Iris volume' },
    {commandResponse : 'OSE:71:', commandName : 'Preset playback range' },
    {commandResponse : 'OSF:', commandName : 'Scene file' },
    {commandResponse : 'OSH:', commandName : 'Shutter' },
    {commandResponse : 'OTP:', commandName : 'Pedestal' },
    {commandResponse : 'OUS:', commandName : '' },
    {commandResponse : 'p', commandName : 'Power On/ Standby' },
    {commandResponse : 'pE00', commandName : 'Preset Entry No.001~040' },
    {commandResponse : 'pE01', commandName : 'Preset Entry No.041~080' },
    {commandResponse : 'pE02', commandName : 'Preset Entry No.081~100' },
    {commandResponse : 'rER', commandName : 'Error information' },
    {commandResponse : 'rt', commandName : '' },
    {commandResponse : 's', commandName : '' },
    {commandResponse : 'sWZ', commandName : 'Zoom position-linked pan/tilt speed adjustment On/Off' },
    {commandResponse : 'TITLE:', commandName : 'Camera name' },
    {commandResponse : 'uPVS', commandName : 'Preset Speed'},
]